name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
      - backend-push   # triggers when backend branch is pushed/merged

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/artisan-backend ./backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy artisan-backend \
            --image gcr.io/${{ secrets.FIREBASE_PROJECT_ID }}/artisan-backend \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
